// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: Apache-2.0

package controls

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// pageTitles are the manual's headings, one per framework.
var pageTitles = map[Framework]string{
	SOC2:     "SOC 2: Trust Services Criteria",
	ISO27001: "ISO/IEC 27001:2022 Annex A",
	GDPR:     "GDPR",
}

// Markdown renders the manual page for the mapping. The page is generated
// from the JSON so the two cannot disagree; `make controls-verify` fails
// the build when the committed page differs from this output.
func (m *Mapping) Markdown(w io.Writer) error {
	p := &printer{w: w}
	p.line("---")
	// REUSE-IgnoreStart
	p.line("# SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>")
	p.line("# SPDX-License-Identifier: Apache-2.0")
	// REUSE-IgnoreEnd
	p.line("description: >-")
	p.linef("  Which %s controls each passmcp check evidences, which it does not, and why. Generated from spec/controls/%s.json.", m.Name, m.Framework)
	p.line("---")
	p.line("")
	p.linef("<!-- Generated by scripts/controlsdoc from spec/controls/%s.json. Do not edit; run `make controls`. -->", m.Framework)
	p.line("")
	p.linef("# %s", pageTitles[m.Framework])
	p.line("")
	p.linef("Framework version: %s.", m.Version)
	p.line("")
	p.line(m.Note)
	p.line("")
	p.line("Every finding in a JSON report carries the controls it evidences under")
	p.linef("`controls.%s`. `passmcp verify --framework %s` reads an attestation offline", m.Framework, m.Framework)
	p.linef("and reports each one below as evidenced, failing or not assessed, and `passmcp evidence --framework %s`", m.Framework)
	p.line("builds a dated evidence bundle from attestations over an audit period.")
	p.line("")
	m.criteriaTable(p)
	m.checksTable(p)
	return p.err
}

func (m *Mapping) criteriaTable(p *printer) {
	byCriterion := map[string][]string{}
	for id, e := range m.Checks {
		for _, c := range e.Controls {
			byCriterion[c] = append(byCriterion[c], id)
		}
	}
	p.line("## Controls")
	p.line("")
	p.line("| Control | Title | Evidenced by |")
	p.line("|---|---|---|")
	for _, c := range m.Criteria {
		cell := "Not covered by passmcp: " + c.Reason
		if checks := byCriterion[c.ID]; len(checks) > 0 {
			sort.Strings(checks)
			cell = codeList(checks)
		}
		p.linef("| %s | %s | %s |", c.ID, escapeCell(c.Title), escapeCell(cell))
	}
	p.line("")
}

func (m *Mapping) checksTable(p *printer) {
	ids := make([]string, 0, len(m.Checks))
	for id := range m.Checks {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	p.line("## Checks")
	p.line("")
	p.line("| Check | Controls |")
	p.line("|---|---|")
	for _, id := range ids {
		e := m.Checks[id]
		cell := strings.Join(e.Controls, ", ")
		if len(e.Controls) == 0 {
			cell = "None: " + e.None
		}
		p.linef("| `%s` | %s |", id, escapeCell(cell))
	}
}

func codeList(ids []string) string {
	out := make([]string, len(ids))
	for i, id := range ids {
		out[i] = "`" + id + "`"
	}
	return strings.Join(out, ", ")
}

func escapeCell(s string) string { return strings.ReplaceAll(s, "|", "\\|") }

type printer struct {
	w   io.Writer
	err error
}

func (p *printer) line(s string) {
	if p.err == nil {
		_, p.err = fmt.Fprintln(p.w, s)
	}
}

func (p *printer) linef(format string, a ...any) { p.line(fmt.Sprintf(format, a...)) }
